<?php
    use Magento\Framework\Escaper;
    use Magento\Catalog\Pricing\Price\FinalPrice;
    use Magento\Catalog\Block\Product\ReviewRendererInterface;
    use Magento\Wishlist\Helper\Data as WishList;
    use Tisa\CatalogWidget\Block\Widget\Multimedia;

    /** @var Multimedia $block */
    /** @var Escaper $escaper */
    $categories = $block->getCategories();
    $wishList = $this->helper(WishList::class)->isAllow();
?>

<?php if (!$categories): ?>
    <?php return ?>
<?php endif ?>

<div class="sub-category-widget">
    <?php if ($categories): ?>
    <div class="category-items">
        <?php foreach ($categories as $categoryGroups): ?>
        <ul class="category-group">
            <li><a href="<?= $categoryGroups[0]->getUrl() ?>"><?= $categoryGroups[0]->getName() ?></a></li>
            <?php foreach ($categoryGroups as $category): ?>
                <li class="category-item">
                    <a href="<?= $category->getUrl()?>"><?= $category->getName() ?></a>
                </li>
            <?php endforeach ?>
        </ul>
        <?php endforeach ?>
    </div>
    <?php endif ?>
</div>
